services:
 mongodb-test:
  image: mongo
  container_name: fancy-mongo-service
  expose:
   - ${MONGO_PORT} # Environmental variable from .env
  
  environment:
   MONGO_INITDB_ROOT_PASSWORD_FILE: run/secrets/mongo_admin_pwd
  
  deploy:
   restart_policy:
     condition: on-failure
     delay: 3s
     max_attempts: 10
     window: 15s
   resources:
    limits:
     cpus: "0.75"
     memory: 175M
    reservations: 
     cpus: "0.25"
     memory: 75M

  secrets:
   - mongo_admin_pwd

  healthcheck:
   test: mongosh --eval "db.adminCommand('ping').ok"
   interval: 6s
   timeout: 5s
   retries: 3

  env_file: .mongo.env

  networks: 
   chrolansk-network:
    aliases:
     - ${MONGO_HOSTNAME}
  
 myApp: 
  image: chrolansk
  build: .
  ports: 
   - 8081:8081
  depends_on:
   mongodb-test:
    condition: service_healthy
    restart: true
  restart: unless-stopped
  environment:
   MONGO_INITDB_ROOT_PASSWORD_FILE: run/secrets/mongo_admin_pwd
  
  env_file:
   - .mongo.env
   - .env
  
  networks:
   - chrolansk-network

  secrets:
   - mongo_admin_pwd

secrets:
 mongo_admin_pwd:
  file: ./secrets.dir/admin_pwd.txt

networks:
 chrolansk-network:

