services:
  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "1814:1814"
  frontend:
    image: frontend:latest
    # image: ninejar/webproject-frontend:local
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend