services:
  mongodb:
    image: mongo:latest
    build: .
    ports:
      - "27017:27017"
  backend:
    image: backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "1814:1814"
    depends_on:
      - mongodb
  frontend:
    image: frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
