services:
  frontend:
    build:
      context: frontend
    ports:
      - 8081:8081
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - react-express
    depends_on:
      - backend
  backend:
    restart: unless-stopped
    build:
      context: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - react-express
    ports:
      - 1814:1814

networks:
  react-express: