services:
  frontend:
    image: ninejar/webproject-frontend:latest
    ports:
      - 8081:8081
    stdin_open: true
    restart: unless-stopped
    networks:
      - react-express
    depends_on:
      - backend
  backend:
    image: ninejar/webproject-backend:latest
    restart: unless-stopped
    networks:
      - react-express
    ports:
      - 8091:8091

networks:
  react-express: