services:
  frontend:
    image: ninejar/webproject-frontend:local
    ports:
      - 8081:8081
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - react-express
    depends_on:
      - backend
  backend:
    image: ninejar/webproject-backend:latest
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - react-express
    ports:
      - 1814:1814

networks:
  react-express: