services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

#    env_file: ./.env
#    environment:
#      MONGO_INITDB_ROOT_PASSWORD_FILE: run/secrets/admin_pwd

#    secrets:
#      - ./secrets.dir/admin_pwd.txt
    ports:
      - "27017:27017"

#    volumes:
#      - ./mydata:/data/db


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "1814:1814"
#    env_file: ./.env
#    environment:
#      MONGO_INITDB_ROOT_PASSWORD_FILE: run/secrets/admin_pwd

    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend

#volumes:
#  mydata: